- platform: template
  lights:
    machine_room_lights:
      friendly_name: "Machine Room Lights"
      value_template: >-
        {{ is_state("switch.machine_room_lights", "on") }}
      turn_on:
        service: switch.turn_on
        entity_id:
          - switch.machine_room_lights
      turn_off:
        service: switch.turn_off
        entity_id:
          - switch.machine_room_lights
