sensor:
  - platform: modem_callerid
    device: /dev/modem

notify:
  - name: caller_id_visual_notify_group
    platform: group
    services:
      - service: living_room_tv
      - service: basement_tv

notify:
  - name: caller_id_audio_notify_group
    platform: group
    services:
      - service: google_home

script:
  normalize_caller_id:
    sequence:
      - service: python_script.set_state
        data:
          entity_id: sensor.normalized_caller_id
        data_template:
          state: "{{ states.sensor.modem_callerid.state }}"
          attributes:
            cid_time: >-
              {{ state_attr("sensor.modem_callerid", "cid_time") }}
            cid_number: >-
              {% set orig = state_attr("sensor.modem_callerid", "cid_number") %}
              {% set len = orig | length %}
              {% if len > 10 %}{{ orig[0:-10] }}-{% endif %}
              {% if len > 7 %}{{ orig[-10:-7] }}-{% endif %}
              {% if len > 4 %}{{ orig[-7:-4] }}-{% endif %}
              {{ orig[-4:] }}
            cid_name: >-
              {% set table = {
                  "3013393369": "Louis Dubeau",
                  "3017887720": "Lisa Solomon",
                }
              %}
              {% set override =
                 table.get(state_attr("sensor.modem_callerid", "cid_number")) %}
              {{ override if override is not none else
                 state_attr("sensor.modem_callerid", "cid_name") }}

automation:
  - alias: Normalize Caller ID
    trigger:
      platform: state
      entity_id: sensor.modem_callerid
    action:
      service: script.normalize_caller_id
  - alias: Notify Caller ID
    trigger:
      platform: state
      entity_id: sensor.normalized_caller_id
      to: "callerid"
    action:
      - service: notify.caller_id_visual_notify_group
        data:
          message: >-
            Call from {{ state_attr('sensor.normalized_caller_id',
                        'cid_name') }}
            at {{ state_attr('sensor.normalized_caller_id', 'cid_number') }}
      - service: notify.caller_id_audio_notify_group
        data:
          message: >-
            Call from
            {{ state_attr('sensor.normalized_caller_id', 'cid_name') }}
