binary_sensor:
  - platform: template
    sensors:
      louis_away:
        # A sensor determining whether louis is away
        friendly_name: Louis is Away
        value_template: >-
          {{ is_state("binary_sensor.away", "on") }}
