notify:
  - name: temperature_notify_group
    platform: group
    services:
      - service: living_room_tv
      - service: basement_tv
      - service: google_home

sensor:
  - platform: template
    sensors:
      next_rising:
        friendly_name: 'Next Rising of the Sun'
        value_template: >-
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | 
             timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      next_setting:
        friendly_name: 'Next Setting of the Sun'
        value_template: >-
          {{ as_timestamp(states.sun.sun.attributes.next_setting) |
             timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down

binary_sensor:
  platform: template
  sensors:
      temperature_too_low:
        friendly_name: The Temperature is Too Low
        device_class: safety
        value_template: >-
          {{ states("sensor.weather_daily_forecast_temperature_low") | float <= 25 }}

input_boolean:
  guest_bathroom_sink_faucet:
    name: "The Sink Faucet in the Guest Bathroom"

script:
  notify_sink_faucet_can_be_turned_on:
    alias: Notify That the Guest Bathroom Sink is Cold
    variables:
      message: "Turn on the guest bathroom sink faucet."
      action: guest_bathroom_sink_faucet_turned_on
    sequence:
      - service: notify.mobile_app_chromebook
        data:
          message: "{{ message }}"
          data:
            ttl: 0
            priority: high
            actions:
              - action: "{{ action }}"
                title: Done
      - service: notify.mobile_app_pixel_4a
        data:
          message: "{{ message }}"
          data:
            ttl: 0
            priority: high
            actions:
              - action: "{{ action }}"
                title: Done
      - service: notify.temperature_notify_group
        data:
          message: "{{ message }}"
      - service: persistent_notification.create
        data:
          message: "{{ message }}"
          notification_id: guest_bathroom_sink_faucet
  notify_sink_faucet_can_be_turned_off:
    variables:
      message: "Turn off the guest bathroom sink faucet."
      action: guest_bathroom_sink_faucet_turned_off
    sequence:
      - service: notify.mobile_app_chromebook
        data:
          message: "{{ message }}"
          data:
            ttl: 0
            priority: high
            actions:
              - action: "{{ action }}"
                title: Done
      - service: notify.mobile_app_pixel_4a
        data:
          message: "{{ message }}"
          data:
            ttl: 0
            priority: high
            actions:
              - action: "{{ action }}"
                title: Done
      - service: notify.temperature_notify_group
        data:
          message: "{{ message }}"
      - service: persistent_notification.create
        data:
          message: "{{ message }}"
          notification_id: guest_bathroom_sink_faucet
    
automation:
  - alias: The Temperature is too Low
    trigger:
      - platform: state
        entity_id: binary_sensor.temperature_too_low
        to: "on"
      - platform: time_pattern
        hours: /1
    # Test that the trigger is a state trigger. This way the warning comes right away
    # and between 17 and 22 on the hour.
    condition: >-
      {% set hour = as_local(now()).hour %}
      {{ (trigger.platform == "state") or
         (is_state('input_boolean.guest_bathroom_sink_faucet', 'off') and
          is_state('binary_sensor.temperature_too_low', 'on') and
          (hour > 16) and
          (hour < 23)) }}
    action:
      - service: script.notify_sink_faucet_can_be_turned_on
  - alias: Can Turn Off the Sink
    trigger:
      - platform: state
        entity_id: input_boolean.guest_bathroom_sink_faucet
        to: "on"
      - platform: time_pattern
        hours: /1
    # We want the warning to only come betwen 9 and 12, inclusively.
    condition: >-
      {% set hour = as_local(now()).hour %}
      {{ is_state('input_boolean.guest_bathroom_sink_faucet', 'on') and
         (hour > 8) and
         (hour < 13) }}
    action:
      - service: script.notify_sink_faucet_can_be_turned_off
  - alias: "Turned On Has Been Fired"
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: guest_bathroom_sink_faucet_turned_on
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_bathroom_sink_faucet
  - alias: "Turned Off Has Been Fired"
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: guest_bathroom_sink_faucet_turned_off
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_bathroom_sink_faucet

          
