alias: "Telegram ping command"
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: "/ping"
action:
  - service: telegram_bot.send_message
    data_template:
      message: "pong"
      target: "{{ trigger.event.data.user_id }}"
