# When we enter the light state, all lights must be turned off. This automation
# may be redundant for some scenarios. Eg. leaving the "up" state turns off the lights
# in the living room already. However, this automation takes care of some
# additional cases. For instance if lights are on when we leave the house,
# and there is light outside this turns them off.
alias: Enter the Light State
trigger:
  - platform: state
    entity_id: sensor.occupancy_cycle
    to: "light"
action:
  - service: light.turn_off
    entity_id: group.rooms
