- platform: template
  lights:
    front_porch:
      friendly_name: "Front Porch"
      value_template: >-
        {{ is_state("switch.front_porch", "on") }}
      turn_on:
        service: switch.turn_on
        entity_id:
          - switch.front_porch
      turn_off:
        service: switch.turn_off
        entity_id:
          - switch.front_porch
