- platform: template
  lights:
    outside_garage_lights:
      friendly_name: "Outside Garage Lights"
      value_template: >-
        {{ is_state("switch.outside_garage_lights", "on") }}
      turn_on:
        service: switch.turn_on
        entity_id:
          - switch.outside_garage_lights
      turn_off:
        service: switch.turn_off
        entity_id:
          - switch.outside_garage_lights
