title: Automation
path: automation
background: black
theme: slate
cards:
  - type: entities
    title: Environment
    entities:
      - alarm_control_panel.area001
      - sensor.time
      - sensor.date
      - binary_sensor.dark_inside
      - binary_sensor.dark_outside
  - type: entities
    title: Presence
    entities:
      - binary_sensor.away
      - binary_sensor.walkway_motion
  - type: entities
    title: Travel
    entities:
      - binary_sensor.travel
      - input_datetime.travel_start
      - input_datetime.travel_end
  - type: entities
    title: Routines
    entities:
      - input_boolean.louis_is_awake
  - type: entities
    title: Occupancy Simulation
    entities:
      - sensor.occupancy_wake_time
      - sensor.occupancy_bed_time
      - sensor.occupancy_sleep_time
      - sensor.occupancy_cycle
  - type: entities
    title: Scripts
    entities:
      - group.all_scripts
  - type: entities
    title: Automations
    entities:
      - group.all_automations
