homeassistant:
  name: Home
  latitude: 39.386434
  longitude: -77.347360
  elevation: 440
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages/

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

http:
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://shunya:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Recorder
recorder:
  purge_keep_days: 7
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.date_time
      - sensor.weather_cloud_coverage
      - sensor.weather_symbol
      - sensor.weather_temperature

# Text to speech
tts:
  - platform: google_translate
    base_url: http://192.168.0.12:8123


wake_on_lan:

cloud: !include cloud.yaml
elkm1: !include elkm1.yaml
zwave: !include zwave.yaml
group: !include_dir_named groups/
automation: !include_dir_list automations/
script: !include_dir_named scripts/
light: !include_dir_merge_list lights/
# scene: !include_dir_merge_list scenes/
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
media_player: !include_dir_list media_players/
input_datetime: !include_dir_named input_datetimes/
weather: !include weather.yaml

lovelace:
  mode: yaml

system_health:

python_script:

mqtt:
  # We do not use SSL for this connection because it is within the network
  # created for our Docker containers.
  broker: mosquitto
  username: ha
  password: !secret mosquitto_password
  discovery: true
  discovery_prefix: ha
