alias: Turn the interior lights off when we are away
trigger:
  platform: state
  entity_id: binary_sensor.away
  from: "off"
  to: "on"
condition:
  # Assume that if we left some lights on when dark, we meant to do that.
  #
  # Actually this needs to be rethought. The problem is that the occupancy
  # simulation code will completely ignore this and will just turn lights on
  # and off.
  condition: state
  entity_id: binary_sensor.dark_inside
  state: "off"
action:
  service: light.turn_off
  entity_id: group.rooms
